
language: c

sudo: false

addons:
        apt:
                packages:
                        - dejagnu
                        - autoconf-archive
                        - libyajl-dev

before_script: echo set verbose 9 > ~/.dejagnurc

script:
        - ./autogen.sh
        - ./configure
        - make clean
        - make all
        - make check

env:
        - CFLAGS=" -Wall -Werror "

